### PR TITLE
rpccall: rewindchain

### PR DESCRIPTION
**Pull request by zeded**
usage: rewindchain (number)
erases (number) of blocks from own blockchain file
taken from other coins. originally from shadowcash.

### CODE REVIEW

**Comment by jprichardson** [comment]
What's the use case?

**Comment by bearsylla** [comment]
@jprichardson My guess is it allows partially rescanning of the blockchain. 

For example, If you imported a new privkey, and you are 100% sure that there is no transaction occurs for the privkey before certain block, you can just "rewind" the chain to that one block prior to the block containing the first tx for that privkey instead of rescanning the entire blockchain.

**Comment by jprichardson** [comment]
@bearsylla If that's the use case, use [`importwallet`](https://bitcoin.org/en/developer-reference#importwallet) and adjust the birth time. That's what I do in Obsidian :)

**Comment by zeded** [comment]
@jprichardson a use case for rewindchain would be if your wallet is on a fork, you would ussually resync the whole blockchain from 0. with this rpccall you can erase a number of blocks from the blockchain file instead of syncing from 0. In this example it would save lots of time. For example syncing the last 1000 blocks instead of 750,000+ blocks.

**Comment by jprichardson** [comment]
@zeded Doesn't Blackcoin-qt handle this automatically?

**Comment by rat4** [comment]
I'd prefer Bitcoin's invalidateblock and reconsiderblock.

**Pull request closed without merging**
